### ISSUE TITLE
Issue for AlgDesign - segfault memory not mapped

### ISSUE THREAD

**Issue by vnijs** [jvbraun/dhmm#1]
I have been using the AlgDesign package for a while for an R/Shiny package (http://vnijs.github.io/radiant/). I have been getting error messages from Travis CI (Linux) that there are memory issues related to AlgDesign (see pasted output below). Works fine on Mac and Windows.

Any idea what might be going on?

> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: summary.conjoint_profiles
> ### Title: Summary method for the conjoint_profiles function
> ### Aliases: summary.conjoint_profiles
> ### *\* Examples
> 
> cp <<- c("price = c('$10','$13','$16')", "sight = c('Staggered','Not Staggered')",
> -        "comfort = c('Average no cupholder','Average cupholder','Large cupholder')",
> -        "audio.visual = c('Small plain','Large plain','Large digital')",
> -        "food = c('No food','Hot dogs and popcorn','Gourmet food')")
>   result <- conjoint_profiles("cp")

 **\* caught segfault ***
address 0x200000012, cause 'memory not mapped'

Traceback:
 1: model.matrix.default(frml, data, ...)
 2: model.matrix.formula(frml, data)
 3: model.matrix(frml, data)
 4: optFederov(data = experiment, nTrials = i, maxIteration = 1000)
 5: ff_design(., itt)
 6: function_list[[k]](value)
 7: withVisible(function_list[[k]](value))
 8: freduce(value, `_function_list`)
 9: `_fseq`(`_lhs`)
10: eval(expr, envir, enclos)
11: eval(quote(`_fseq`(`_lhs`)), env, env)
12: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
13: sample(cap_attr) %>% ff_design(itt)
14: conjoint_profiles("cp")
aborting ...
Segmentation fault
*\* found \donttest examples: check also with --run-donttest
- checking for unstated dependencies in â€˜testsâ€™ ... OK
- checking tests ... OK
  Running â€˜testthat.Râ€™
- checking PDF version of manual ... OK
- DONE
  Status: 1 ERROR, 1 WARNING, 3 NOTEs
  travis_time:end:06ae5a00:start=1441050818232921411,finish=1441050818294261524,duration=61340113
  [0Ktravis_time:start:119e4b58
  [0K$ for name in $(find "${RCHECK_DIR}" -type f -name "*fail"); do echo ">>> Filename: ${name} <<<"; cat ${name}; done
  travis_time:end:119e4b58:start=1441050818301468471,finish=1441050818313066348,duration=11597877
  [0KR CMD check failed

**Comment by jvbraun** [comment]
Hmm...  Not sure yet.  Could you move this issue to the AlgDesign repository and delete this one, though.

**Comment by vnijs** [comment]
Sorry to 'cross-post' this issue. I'd be happy move this issue but there does not seem to be an 'issues' link for the AlgDesign repo.

**Comment by jvbraun** [comment]
You are right!  It should be available now.

**Comment by vnijs** [comment]
Move the issue to the AlgDesign repo. Thanks @jvbraun!
